### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by kwhitefoot** [trustable-code/NiCalc#3]
I installed NiGui using nimble like this:

D:\home\kj>cd bin\nim-1.0.2

D:\home\kj\bin\nim-1.0.2>bin\nimble.exe install nigui
Downloading https://github.com/trustable-code/NiGui using git
  Verifying dependencies for nigui@0.2.5
 Installing nigui@0.2.5
   Success: nigui installed successfully.

then I downloaded the NiCalc source: https://github.com/trustable-code/NiCalc/archive/refs/tags/1.2.zip

I unpacked the source, opened a cmd window and tried to compile and got this:

D:\home\kj\onedrive\Documents\NiCalc-1.2\NiCalc-1.2\src>nim compile NiCalc.nim
Hint: used config file 'D:\home\kj\bin\nim-1.0.2\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: NiCalc [Processing]
Hint: nigui [Processing]
Hint: windows [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: time_t [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: utils [Processing]
D:\home\kj\onedrive\Documents\NiCalc-1.2\NiCalc-1.2\src\NiCalc.nim(96, 38) Error: undeclared identifier: 'ControlKeyEvent'

I've searched the source of nigui and I couldn't find ControlKeyEvent.

I'm not familiar with nim or nigui so I suspect that I have misunderstood something but I have no idea what.

Can you give me a hint?

**Comment by simonkrauter** [comment]
The identifier ``ControlKeyEvent``was renamed in NiGui. 
Please use the latest NiCalc code from master branch. This is compatible with the latest NiGui code.
